version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8123:8123"
    expose:
      - 8123
    volumes:
      - .:/tmp
    depends_on:
      - postgres
    entrypoint: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]


