version: '2.1'

networks:
  app:

services:
  postgres_db:
    image: postgres:10
    container_name: postgres-db-container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app
    ports:
      - "5432:5432"
  app:
    image: angular-spring-boot-image
    container_name: angular-spring-boot-container
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    build: .
    volumes:
      - .:/tmp
    depends_on:
      - postgres_db
    networks:
      - app
    expose:
      - 8123
    ports:
      - "8123:8123"
    entrypoint: ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]


